Repository mattn/go-sqlite3, pull requests merged in 2018-06, with the labels that each got.

#558 Adds GetFilename (sqlite3_db_filename) to SqliteConn
  sqlite3.go
Labels: enhancement

#574 Follow official Release Policy
  .travis.yml
  README.md
Labels: research

#594 fix/511
  README.md
Labels: documentation

#592 fix/test/coverage
  sqlite3.goconvey
  sqlite3_func_crypt_test.go
  sqlite3_go18_test.go
  sqlite3_opt_userauth_test.go
  upgrade/profile.goconvey
Labels: enhancement
